### ISSUE TITLE
Exception from compact method

### ISSUE THREAD

**Issue by ffdb42** [hivedb/hive#1124]
I was running my code to gather some statistics (it wasn't connected with hive) for like an hour and I got this exception which ruined all process: 
`Unhandled exception:
FileSystemException: Cannot rename file to 'C:\Users\faufd\Desktop\sh\cpp_native\example\uploadbox-v1.0.hive', path = 'C:\Users\faufd\Desktop\sh\cpp_native\example\uploadbox-v1.0.hivec' (OS Error: Access denied.
, errno = 5)
#0      _File.rename.<anonymous closure> (dart:io/file_impl.dart:305:9)
<asynchronous suspension>
#1      StorageBackendVm.compact.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:188:7)
<asynchronous suspension>
#2      BoxBaseImpl.compact (package:hive/src/box/box_base_impl.dart:151:5)
<asynchronous suspension>
#3      BoxImpl._writeFrames (package:hive/src/box/box_impl.dart:95:5)
<asynchronous suspension>`
I have 2 files in this directory `uploadbox-v1.0.hive` and `uploadbox-v1.0.hivec`, `compact()` method was called on background by hive.

**Comment by AnAlpaca** [comment]
I am currently experiencing this very issue. My first thought was permissions, so I changed from storing the file in C:\Users\<user>\AppData\Roaming to within the msix container in C:\Program Files\WindowsApps\<Appname>, but this definitely did NOT help. So my next thought is that the file is in use by another process (such as the app itself) and thus windows is blocking the the rename, but this is something I cant really solve. Any insights from others would be extremely helpful. 

Also another side note, I tested this on 2 windows 11 pc's and it seemed to run just fine, but when I run this on 2 different colleagues windows 10 machines then this issue occurs

**Comment by ffdb42** [comment]
> I am currently experiencing this very issue. My first thought was permissions, so I changed from storing the file in C:\Users<user>\AppData\Roaming to within the msix container in C:\Program Files\WindowsApps<Appname>, but this definitely did NOT help. So my next thought is that the file is in use by another process (such as the app itself) and thus windows is blocking the the rename, but this is something I cant really solve. Any insights from others would be extremely helpful.
> 
> Also another side note, I tested this on 2 windows 11 pc's and it seemed to run just fine, but when I run this on 2 different colleagues windows 10 machines then this issue occurs

I had already forgotten that I had such a problem. Unfortunately, I can't even tell you if I found any solution then, good luck in the search

**Comment by AnAlpaca** [comment]
Hahaha I completely understand. For anyone else looking here, it does seem like because I provide a path, the backend manager selects a storage backend implementation that supports compaction. This compaction is doing the rename that fails. Not sure of the fix, but there needs to be a way to declare supportsCompaction or override this somehow? I could be speaking out of line here though.
