### ISSUE TITLE
HiveCollections crash on second open

### ISSUE THREAD

**Issue by krille-chan** [hivedb/hive#1162]
**Steps to Reproduce**
This happens on the latest main branch to me. 2.2.3 seems not to be affected. Just create a HiveCollection-Box, write something to it and then restart your application and open it for the second time (in my case it was encrypted). It will throw this exception:

```sh
LateInitializationError: Field 'registry' has already been initialized.
#0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:195:5)
#1      StorageBackendVm.registry= storage_backend_vm.dart:49
#2      StorageBackendVm.initialize storage_backend_vm.dart:79
#3      BoxBaseImpl.initialize box_base_impl.dart:96
#4      HiveImpl._openBox hive_impl.dart:110
#5      HiveImpl.openLazyBox hive_impl.dart:165
#6      CollectionBox._getBox box_collection.dart:143
```

**Code sample**
Just HiveCollections sample

**Version**
 - Platform: iOS
 - Flutter version: [e.g. 3.7.5]
 - Hive version: [e.g. 0.5.0]

**Comment by krillefear** [comment]
With Braids fix I ran now into this:

```sh
[Matrix] Capture exception - Exception: Out of Memory
#0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2245:3)
#1      BufferedFileReader.loadBytes (package:hive/src/io/buffered_file_reader.dart:73:18)
#2      _KeyReader._load (package:hive/src/io/frame_io_helper.dart:89:40)
#3      _KeyReader.readKeys (package:hive/src/io/frame_io_helper.dart:69:31)
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:36)
#5      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:204:15)
#6      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:24)
#7      _rootRunUnary (dart:async/zone.dart:1406:47)
#8      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:204:15)
#9      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:114:48)
#10     _rootRun (dart:async/zone.dart:1398:13)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by krille-chan** [comment]
Follow up: I can still reproduce the bug on current main branch. Tested on Android and iOS:

```sh
LateInitializationError: Field 'registry' has already been initialized.
I/flutter (14725): #0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:195:5)
I/flutter (14725): #1      StorageBackendVm.registry=
storage_backend_vm.dart:49
I/flutter (14725): #2      StorageBackendVm.initialize
storage_backend_vm.dart:79
I/flutter (14725): #3      BoxBaseImpl.initialize
box_base_impl.dart:96
I/flutter (14725): #4      HiveImpl._openBox
hive_impl.dart:109
I/flutter (14725): #5      HiveImpl.openLazyBox
hive_impl.dart:167
I/flutter (14725): #6      CollectionBox._getBox
box_collection.dart:144
I/flutter (14725): #7      CollectionBox.getAll
box_collection.dart:203
I/flutter (14725): #8      HiveCollectionsDatabase.getRoomList.<anonymous closure>
hive_collections_database.dart:544
I/flutter (14725): <asynchronous suspension>
I/flutter (14725): #9      runBenchmarked
```

To reproduce: Create a new HiveCollection Box, open it, write something into it and close it. After second reopening, this error appears
