### ISSUE TITLE
HiveError: Could not read value from box. Maybe your box is corrupted.

### ISSUE THREAD

**Issue by AndreHaueisen** [hivedb/hive#1209]
Hi. I'm getting this exception in production, but I can't figure out why it is happening and I haven't been able to reproduce it in dev. Do you have any insights into when this exception is thrown?

![Screenshot 2023-06-02 at 10 02 33](https://github.com/hivedb/hive/assets/13854934/6b4285ec-a857-4309-880b-49a2d82bf98e)

It appears it happens when line 49 tries to access my box.

![Screenshot 2023-06-02 at 10 07 16](https://github.com/hivedb/hive/assets/13854934/8f8f7ca6-cbfd-4862-8ae8-cbbf9cba173e)

I'd appreciate any tips you think might be relevant.

**Comment by anidotnet** [comment]
I am also getting similar error while running my test in github ci windows box:

```
Failed to put vel: [[1691177347124887552]NO₂, [1691177349456920577]NO₂, [1691177350023151616]NO₂] pair in $nitrite_index|Employee|employeeNote.text|Fulltext
 #0      StorageBackendVm.readValue.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:114:9)
 <asynchronous suspension>
 #1      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
 <asynchronous suspension>
 
 Caused by: HiveError: Could not read value from box. Maybe your box is corrupted.
```

I am using `LazyBox` to store my data.

This error is intermittent and it is happening only in github ci windows box. In my Windows (x64) dev machine, I am not seeing this issue, also neither in my Ubuntu (x64) or MacOS (m2) machine. Hope this info helps.

**Comment by mdanics** [comment]
I'm also encountering this same issue,  using `dio_cache_manager` with flutter_map. Did you ever solve this?

**Comment by flodaniel** [comment]
We are also seeing this error, here is our stacktrace:

```log
HiveError: HiveError: Could not read value from box. Maybe your box is corrupted.
  File "storage_backend_vm.dart", line 114, in StorageBackendVm.readValue.<fn>
  File "<asynchronous suspension>"
  File "future_impl.dart", line 41, in _AsyncCompleter.complete
  File "<asynchronous suspension>"
  File "lazy_box_impl.dart", line 32, in LazyBoxImpl.get
  File "<asynchronous suspension>"
  File "dio_cache_interceptor.dart", line 186, in DioCacheInterceptor._loadCacheResponse
  File "<asynchronous suspension>"
  File "dio_cache_interceptor.dart", line 47, in DioCacheInterceptor.onRequest
```

We also use Hive in other parts of our app but the stacktrace is always from the `dio_cache_interceptor`

**Comment by oscarshaitan** [comment]
same here we only got the issue while using `dio_cache_interceptor`
and also is always 
![image](https://github.com/isar/hive/assets/9093952/84a34f46-8e97-4d48-bc5b-7ea8f3c86994)
dio_cache_interceptor_hive_store.dart

**Comment by flodaniel** [comment]
I will now try to create the `HiveCacheStore` from `dio_cache_interceptor` soon as the app starts. Previously we only created it when we needed it and my theory is that the `HiveCacheStore` `clean()` method is still running while it it is already being used, leading to this error as the value is removed and accessed at the same time.

**Comment by ibraheemalayan** [comment]
I have the same issue reported via sentry many times 

> `hive: 2.2.3`
> `dio_cache_interceptor_hive_store:3.2.2`

<img width="1026" alt="Screenshot 2024-08-14 at 20 59 59" src="https://github.com/user-attachments/assets/8625bd20-2527-4759-b7f3-7090ca88d792">

**Comment by ibraheemalayan** [comment]
Update: 

I got the same bug after deleting app, reinstalling it.

**Comment by ch1025540473** [comment]
<img width="557" alt="Image" src="https://github.com/user-attachments/assets/fd910562-30c6-43ca-a41d-68e0065621f9" />

i have the same bug at hive version: "2.2.3",how to resolve it

**Comment by flerovium11** [comment]
> I will now try to create the HiveCacheStore from dio_cache_interceptor soon as the app starts. Previously we only created it when we needed it and my theory is that the HiveCacheStore clean() method is still running while it it is already being used, leading to this error as the value is removed and accessed at the same time.

@flodaniel did it work? Getting the same error in my flutter app using http_cache_hive_store
