### ISSUE TITLE
Unhandled Exception: Out of Memory

### ISSUE THREAD

**Issue by ahir504** [hivedb/hive#1273]
E/flutter (25087): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Out of Memory
E/flutter (25087): #0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2237:3)
E/flutter (25087): #1      BufferedFileReader.loadBytes (package:hive/src/io/buffered_file_reader.dart:73:18)
E/flutter (25087): #2      _KeyReader._load (package:hive/src/io/frame_io_helper.dart:89:40)
E/flutter (25087): #3      _KeyReader.readKeys (package:hive/src/io/frame_io_helper.dart:69:31)
E/flutter (25087): #4      _rootRunUnary (dart:async/zone.dart:1407:47)
E/flutter (25087): #5      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
E/flutter (25087): #6      _FutureListener.handleValue (dart:async/future_impl.dart:162:18)
E/flutter (25087): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
E/flutter (25087): #8      Future._propagateToListeners (dart:async/future_impl.dart:875:13)
E/flutter (25087): #9      Future._completeWithValue (dart:async/future_impl.dart:647:5)
E/flutter (25087): #10     _rootRunUnary (dart:async/zone.dart:1407:47)
E/flutter (25087): #11     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
E/flutter (25087): #12     _FutureListener.handleValue (dart:async/future_impl.dart:162:18)
E/flutter (25087): #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
E/flutter (25087): #14     Future._propagateToListeners (dart:async/future_impl.dart:875:13)
E/flutter (25087): #15     Future._completeWithValue (dart:async/future_impl.dart:647:5)
E/flutter (25087): #16     _rootRunUnary (dart:async/zone.dart:1407:47)
E/flutter (25087): #17     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
E/flutter (25087): #18     _FutureListener.handleValue (dart:async/future_impl.dart:162:18)
E/flutter (25087): #19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
E/flutter (25087): #20     Future._propagateToListeners (dart:async/future_impl.dart:875:13)
E/flutter (25087): #21     Future._completeWithValue (dart:async/future_impl.dart:647:5)
E/flutter (25087): #22     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:721:7)
E/flutter (25087): #23     _rootRun (dart:async/zone.dart:1399:13)
E/flutter (25087): #24     _CustomZone.run (dart:async/zone.dart:1301:19)
E/flutter (25087): #25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233:23)
E/flutter (25087): #26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (25087): #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by YassinNouh21** [comment]
@ahir504  did u find a solution for this

**Comment by mhmdkayyali** [comment]
I am getting this as well:
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Out of Memory
