### ISSUE TITLE
Inherited types cast error

### ISSUE THREAD

**Issue by re-bola** [hivedb/hive#185]
**Steps to Reproduce**
Please tell me exactly how to reproduce the problem you are running into.

```

@HiveType(typeId: 206)
class GenericService extends HiveObject {
  @HiveField(0)
  MultiLangText title;

  // Includes everythingin the order it should be.
  @HiveField(1)
  HiveList<ServiceItem> serviceItems;

  GenericService();
  GenericService.from(this.title, this.serviceItems);
}

@HiveType(typeId: 195)
class SpecailService extends GenericService {
  @HiveField(3)
  int  something;
  SpecailService ();

  SpecailService .from(this.hour, MultiLangText title, HiveList<ServiceItem> serviceItems)
      : super.from(title, serviceItems);
}
```

I populated a hive without any problems. When I cam to call box.get I got the following issue:

```
I/flutter (26088): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (26088): The following _CastError was thrown building FutureBuilder<dynamic>(dirty, state:
I/flutter (26088): _FutureBuilderState<dynamic>#ac490):
I/flutter (26088): type 'GenericService' is not a subtype of type 'SpecailService ' in type cast
I/flutter (26088):
I/flutter (26088): The relevant error-causing widget was:
I/flutter (26088):   FutureBuilder<dynamic>
I/flutter (26088):   file:///C:/Users/*****************************
I/flutter (26088):
I/flutter (26088): When the exception was thrown, this was the stack:
I/flutter (26088): #0      BoxImpl.get (package:hive/src/box/box_impl.dart:34:26)
I/flutter (26088): #1      HiveListImpl.delegate (package:hive/src/object/hive_list_impl.dart:84:25)

```

**Version**
 - Platform: Windows
 - Flutter version:1.13.6-pre.44
 - Hive version:  ^1.3.0
  hive_generator: ^0.7.0

**Comment by leisim** [comment]
Could you please provide the code of the `ServiceItem` class?

**Comment by re-bola** [comment]
nevermind. I think I just forgot the HiveType annotation.
