### ISSUE TITLE
I'm already register an adapter but it's show my HiveError "Did you forget to register an adapter?"

### ISSUE THREAD

**Issue by Alyahya-A** [hivedb/hive#205]
**Question**
I'm already register an adapter, and everything work good, I can add and delete Objects from my database. But when I rerun my app and try to add Object to DB it's show me an error (just for the first time when I run my app) ```HiveError (HiveError: Cannot write, unknown type: Section. Did you forget to register an adapter?)```. After my app paused and show my that error I press continue (in VSCode) the app work good and now I can add Objects.

**Code sample**
```dart
Hive.registerAdapter(CourseAdapter());
```

```dart
dependencies:
  hive: ^1.3.0
  path_provider: ^1.5.1

dev_dependencies:
  build_runner: ^1.0.0
  hive_generator: ^0.7.0
```

**Version**
 - Flutter version: [1.12.13+hotfix.7]
 - Hive version: [1.3.0]

**Comment by leisim** [comment]
Does the `Course` object contain a parameter with the type `Section` or are you trying to store a `Section` object somewhere else? It seems like you do and Hive does not know how to store it because you did not register a `SectionAdapter`.

**Comment by Alyahya-A** [comment]
Yes, it does contain ``` List<Section>```.
Thank you, you solved this error but another error occurred:
My Section class has field of type ```Exam```:
 
```import 'package:flutter/foundation.dart';
import 'package:hive/hive.dart';

part 'exam.g.dart';

@HiveType(typeId: 3)
class Exam {
  @HiveType(typeId: 0)
  double id; // id is refer to exam order. (1=mid1,2=mid2,3=final)
  @HiveType(typeId: 1)
  final String type;
  @HiveType(typeId: 2)
  final Timestamp startTime;
  @HiveType(typeId: 3)
  String examRoom;
  @HiveType(typeId: 4)
  final String supervisor;

  Exam({
    @required this.type,
    @required this.startTime,
    @required this.examRoom,
    @required this.supervisor,
  })
}

```
When I enter this command: ```flutter packages pub run build_runner build```.
It's successful for ```Course``` and ```Section``` classes, but for ```Exam``` is not, it show me this:
```
PS C:\Projects\Flutter\exams> flutter packages pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 380ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 16.7s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.3s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 5.2s elapsed, 0/16 actions completed.
[INFO] Generating SDK summary completed, took 5.2s

[INFO] 6.3s elapsed, 0/16 actions completed.
[INFO] 7.4s elapsed, 0/16 actions completed.
[INFO] 8.4s elapsed, 0/16 actions completed.
[INFO] 9.4s elapsed, 0/16 actions completed.
[INFO] 10.7s elapsed, 0/16 actions completed.
[INFO] 11.7s elapsed, 0/16 actions completed.
[INFO] 12.9s elapsed, 0/16 actions completed.
[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/courses_page_appbar.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/circl_tab_indicator.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/custom_app_bar.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] hive_generator:hive_generator on lib/screens/my & all courses pages/grid_courses.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] hive_generator:hive_generator on lib/screens/my & all courses pages/course_information.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/course_card.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] hive_generator:hive_generator on lib/screens/my & all courses pages/all_courses_page.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/get_courses.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/get_exams.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/get_num_exams.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/user_courses.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[INFO] 19.9s elapsed, 15/22 actions completed.
[INFO] Running build completed, took 20.7s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 72ms

[SEVERE] Failed after 20.7s
pub finished with exit code 1
```

and the output of ```exam.g.dart``` is:
```
part of 'exam.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class ExamAdapter extends TypeAdapter<Exam> {
  @override
  final typeId = 3;

  @override
  Exam read(BinaryReader reader) {
    var numOfFields = reader.readByte();
    var fields = <int, dynamic>{
      for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Exam(); // missing parameters!
  }

  @override
  void write(BinaryWriter writer, Exam obj) {
    writer..writeByte(0);
  }
}
```

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  hive_generator: ^0.7.0
  analyzer: 0.38.2
```

**Comment by leisim** [comment]
Could you please post the output of the command `flutter packages pub run build_runner build -v`.

**Comment by Alyahya-A** [comment]
Here:
```
PS C:\Projects\Flutter\exams> flutter packages pub run build_runner build -v
[INFO] Generating build script...
[INFO] Generating build script completed, took 424ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 107ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 1.5s

[INFO] Build:Running build...
[INFO] Heartbeat:1.0s elapsed, 0/3 actions completed.
[INFO] Heartbeat:6.8s elapsed, 0/3 actions completed.
[INFO] Build:Running build completed, took 6.8s

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 46ms

[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/courses_page_appbar.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] hive_generator:hive_generator on lib/screens/my & all courses pages/course_information.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] hive_generator:hive_generator on lib/screens/my & all courses pages/all_courses_page.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/custom_app_bar.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] hive_generator:hive_generator on lib/screens/my & all courses pages/grid_courses.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/get_courses.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/circl_tab_indicator.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/course_card.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/get_num_exams.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/user_courses.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] hive_generator:hive_generator on lib/widgets/my & all courses widgets/get_exams.dart (cached):

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
dart:core                                                               Object.noSuchMethod
package:analyzer/src/dart/analysis/driver.dart 632:23                   AnalysisDriver.getLibraryByUri
package:build_resolvers/src/resolver.dart 104:20                        AnalyzerResolver.libraryFor
package:build_resolvers/src/resolver.dart 73:17                         PerActionResolver.libraryFor
package:build                                                           BuildStepImpl.inputLibrary
package:source_gen/src/builder.dart 66:33                               _Builder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36           _SingleBuild._runBuilder
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._matchingPrimaryInputs

[SEVERE] Build:
Failed after 7.0s
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:323:7)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:264:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by Alyahya-A** [comment]
ohhhh sorry. I found why the ```ExamAdapter``` have missing parameters, because I used ```@HiveType()``` instead of ```  @HiveField()``` 🤦🏻‍♂️🤦🏻‍♂️. Now it's work fine but still give me the same error I don't know why. But now I can use Hive features, add, delete, etc.

Thank you a lot for helping me and for this amazing package

**Comment by Alyahya-A** [comment]
Hi again @leisim  :)

After I run the previous command I get error:
```
Target of URI doesn't exist: 'package:exams/screens/all_courses_page.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.
```
The ```all_courses_page.dart``` file is already exist in ```lib``` folder.

Is this error related to this command ```flutter packages pub run build_runner build```? 
Thank you :)

**Comment by leisim** [comment]
Did you maybe mix relative and absolute imports?

**Comment by Alyahya-A** [comment]
I solved this error by moving this file to another folder inside lib.

Thank you again 💝🌹
