### ISSUE TITLE
RangeError when using deleteAt

### ISSUE THREAD

**Issue by DeadlyMissile** [hivedb/hive#317]
So I am using deletAt to delete an element from my box but I keep RangeError: Index out of range why is that? However the object is deleted successfully  and at the correct position

**Comment by leisim** [comment]
Could you please share a small sample which reproduces the error?

**Comment by buraktabn** [comment]
I'm having the same issue with the latest version of the Hive (1.4.4+1). 

My code:
```dart
Future<BasicResponse> createUser(CreateUserInput input) async {
  ...
  if (response.success) {
    await _box.deleteAt(0);
    await _box.add(UserHive.fromMap(_mapToCamelCase(input.toJson()))..id = response.id);
  }
}
```

I know that the index of 0 doesn't exist when I run the  `_box.deleteAt(0)`. According to the source code's docs, it shouldn't throw any error. What I'm trying to is that I want to overwrite the first object and the first index can be empty sometimes. Therefore I got the error below.

https://github.com/hivedb/hive/blob/59ad5403593283233d922f62f76832c64fa33a3b/hive/lib/src/box/box_base.dart#L100-L103

```
[   +8 ms] E/flutter ( 5018): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: RangeError (index): Index out of range: no indices are valid: 0
[        ] E/flutter ( 5018): #0      RangeError.checkValidIndex (dart:core/errors.dart:325:7)
[        ] E/flutter ( 5018): #1      IndexableSkipList._getNodeAt (package:hive/src/util/indexable_skip_list.dart:196:16)
[        ] E/flutter ( 5018): #2      IndexableSkipList.getAt (package:hive/src/util/indexable_skip_list.dart:188:25)
[        ] E/flutter ( 5018): #3      Keystore.getAt (package:hive/src/box/keystore.dart:112:19)
[        ] E/flutter ( 5018): #4      BoxBaseImpl.deleteAt (package:hive/src/box/box_base_impl.dart:129:32)
[        ] E/flutter ( 5018): #5      MeService.createUser (package:myapp/services/graphql/me.service.dart:93:18)
[        ] E/flutter ( 5018): <asynchronous suspension>
[        ] E/flutter ( 5018): #6      AuthVerifyService.signInWithPhoneNumber (package:myapp/services/pages/auth/verify.service.dart:149:22)
[        ] E/flutter ( 5018): <asynchronous suspension>
```
