### ISSUE TITLE
Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.

### ISSUE THREAD

**Issue by amirmhmdi** [hivedb/hive#379]
**Steps to Reproduce**
when app open i want to open a box and inital to static var but it give me this err:

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
E/flutter (16988): #0      BinaryReaderImpl.readFrame 
package:hive/…/binary/binary_reader_impl.dart:249
E/flutter (16988): #1      FrameHelper.framesFromBytes 
package:hive/…/binary/frame_helper.dart:17
E/flutter (16988): #2      FrameIoHelper.framesFromFile 
package:hive/…/io/frame_io_helper.dart:41
E/flutter (16988): <asynchronous suspension>
E/flutter (16988): #3      StorageBackendVm.initialize 
package:hive/…/vm/storage_backend_vm.dart:82
E/flutter (16988): <asynchronous suspension>
E/flutter (16988): #4      BoxBaseImpl.initialize 
package:hive/…/box/box_base_impl.dart:90
E/flutter (16988): #5      HiveImpl._openBox 
package:hive/src/hive_impl.dart:90
E/flutter (16988): <asynchronous suspension>
E/flutter (16988): #6      HiveImpl.openBox 
package:hive/src/hive_impl.dart:111
E/flutter (16988): #7      dBInitial 
package:flutter_app_instagram/main.dart:87
E/flutter (16988): <asynchronous suspension>
E/flutter (16988): #8      main 
package:flutter_app_instagram/main.dart:61
E/flutter (16988): #9      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:241:25)
E/flutter (16988): #10     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter (16988): #11     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (16988): #12     _runZoned  (dart:async/zone.dart:1619:10)
E/flutter (16988): #13     runZonedGuarded  (dart:async/zone.dart:1608:12)
E/flutter (16988): #14     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:233:5)
E/flutter (16988): #15     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (16988): #16     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)

**Code sample**
```
Provide a few simple lines of code to show your problem.
```

**Version**
 - Platform:  Android
 - Flutter version: [1.17.5]
 - Hive version: [1.4.1+1]

**Comment by TheMisir** [comment]
Could you try clearing app storage and re-running the code? Stored data might be crashed or invalid.
