### ISSUE TITLE
MissingPluginException when calling Hive.initFlutter() on Android

### ISSUE THREAD

**Issue by joaovirgili** [hivedb/hive#415]
**Steps to Reproduce**
It works on Android in debug/release mode but doesn't work when i upload an app bundle to play store. When testing iOS with testflight if works perfectly.

Error:
```
2020-08-25 12:30:45.826 4287-4317/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
    <asynchronous suspension>
    #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:109)
    <asynchronous suspension>
    #2      HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:11)
    <asynchronous suspension>
    #3      HiveService.init (package:meddy_paciente/app/shared/services/hive_service.dart:10)
    <asynchronous suspension>
    #4      main (package:meddy_paciente/dev.dart:14)
    <asynchronous suspension>
```

I'm calling `Hive.initFlutter();` in the main function before `runApp`;

```
Future<void> main() async {
  AppConfig.flavor = Flavor.DEV;
  WidgetsFlutterBinding.ensureInitialized();
  await HiveService.init();
  await Firebase.initializeApp(
    options: Platform.isIOS || Platform.isMacOS
        ? AppConfig.firebaseAppleOptionsDev
        : AppConfig.firebaseAndroidOptionsDev,
  );
  tz.initializeTimeZones();

  runApp(ModularApp(module: AppModule()));
}

class HiveService extends Disposable {
  static init() async {
    await Hive.initFlutter();
    await Hive.openBox<bool>("config");
    await Hive.openBox<DateTime>("call");
    print("[HIVE] - Iniciado");
  }
}
```
**Version**
 - Platform: Android
 - Flutter version: 1.20.2
 - hive: ^1.4.2
 - hive_flutter: ^0.3.1

**Comment by joaovirgili** [comment]
I guess this is related to this https://github.com/flutter/flutter/issues/46679

**Comment by TheMisir** [comment]
It happened to me too one time. The issue was one of the plugin was not initialized correctly which break other plugin initializations. (facebook login in my case, i had forgot to add required metas to manifest). So after fixing the issue on fb_login other plugins worked as well.

I removed last added dependencies and added one by one to check which one causes the issue.

**Comment by Dhi13man** [comment]
For me the issue seems to occur only when I'm trying to combine Hive and Firebase for giving the choice between Local Database (Hive in my case) or Cloud Database (Firestore) to the user, and doesn't occur if I am only trying to use the local Database.

Setting the following in app level `build.gradle` is another viable workaround for anyone facing this with `Gradle version 6+` with `path_provider` (or packages depending on it) and Firebase. 

```
android {
    ...

    buildTypes {
        release {
            ...
            minifyEnabled false
            shrinkResources false
        }
    }
}
```

Opinion: I'd guess, the bulkiness of Firebase is messing up the code shrinking in release builds. That is breaking Path Provider, which in my case is breaking Hive.

**Comment by theisoft** [comment]
Ive been working for this for hours and was able to fix it
 
- deleted pubspec.lock
- flutter clean
- flutter pub get

**Comment by AnikethMohan** [comment]
Hey I am also facing the same issue on the more newer version flutter can someone help me out .
