### ISSUE TITLE
initFlutter and getting initialize error

### ISSUE THREAD

**Issue by MahdiPishguy** [hivedb/hive#439]
which version of hive for flutter used in this sample:

https://github.com/hivedb/samples/blob/master/todo/lib/main.dart

???

i get initialize error for hive:

```dart
Hive.initFlutter();

Hive.registerAdapter(UserAdapter());
Hive.registerAdapter(FavoritesAdapter());
```

**Comment by TheMisir** [comment]
Could you please write error message and stack trace here?

**Comment by MahdiPishguy** [comment]
i get this error:

```
Launching lib\main.dart on WAS LX1A in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Waiting for WAS LX1A to report its views...
Debug service listening on ws://127.0.0.1:49213/HET3sReYkzw=/ws
Syncing files to device WAS LX1A...
E/flutter (11192): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: HiveError: You need to initialize Hive or provide a path to store the box.
E/flutter (11192): #0      BackendManager.open (package:hive/src/backend/vm/backend_manager.dart:16:7)
E/flutter (11192): #1      HiveImpl._openBox (package:hive/src/hive_impl.dart:96:30)
E/flutter (11192): #2      HiveImpl.openBox (package:hive/src/hive_impl.dart:135:18)
E/flutter (11192): #3      main (package:rasa_rayaneh_aseman/main.dart:44:27)
E/flutter (11192): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (11192): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (11192): #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (11192): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (11192): #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (11192): #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (11192): #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (11192): #11     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (11192): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (11192): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (11192): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (11192): #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (11192): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (11192): 
E/flutter (11192): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: HiveError: You need to initialize Hive or provide a path to store the box.
E/flutter (11192): #0      BackendManager.open (package:hive/src/backend/vm/backend_manager.dart:16:7)
E/flutter (11192): #1      HiveImpl._openBox (package:hive/src/hive_impl.dart:96:30)
E/flutter (11192): #2      HiveImpl.openBox (package:hive/src/hive_impl.dart:135:18)
E/flutter (11192): #3      main (package:rasa_rayaneh_aseman/main.dart:44:27)
E/flutter (11192): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (11192): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (11192): #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (11192): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (11192): #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (11192): #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (11192): #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (11192): #11     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (11192): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (11192): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (11192): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (11192): #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (11192): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (11192): 
```

my code:

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  Routes.createRoutes();

  final appDocumentDirectory = await path_provider.getApplicationDocumentsDirectory();
  final settings = ApplicationSettings(await StreamingSharedPreferences.instance);

  //Hive.init(appDocumentDirectory.path);
  Hive.initFlutter();

  Hive.registerAdapter(UserAdapter());
  Hive.registerAdapter(FavoritesAdapter());

  final user = await Hive.openBox<User>('user');
  await Hive.openBox<Favorites>('favorites');

  //user.clear();

  independentServices.add(
    Provider(create: (_) => settings),
  );

  runApp(MultiProvider(providers: providers, child: StartupApplication()));
}
```

**Comment by TheMisir** [comment]
Could you try awaiting `initFlutter()`?

**Comment by MahdiPishguy** [comment]
@TheMisir 

```dart
//Hive.init(appDocumentDirectory.path);
await Hive.initFlutter(appDocumentDirectory.path);
```

i think problem solved, in examples `await` not specified, why?

**Comment by TheMisir** [comment]
> @TheMisir 
> 
> ```dart
> //Hive.init(appDocumentDirectory.path);
> await Hive.initFlutter(appDocumentDirectory.path);
> ```
> 
> i think problem solved, in examples `await` not specified, why? 

The tutorials were written a year ago. Probably before `initFlutter` function was added. I don't know exact reason cause I started maintaining just 3 months ago.

I'm glad your issue was fixed 🙂

**Comment by MahdiPishguy** [comment]
@TheMisir

> The tutorials were written a year ago. Probably before `initFlutter` function was added. I don't know exact reason cause I started maintaining just 2 months ago.
> 

Yes i read the library maintainers messages in this repository, i wish you success, thanks in advance
