### ISSUE TITLE
HiveError: To use this list, you have to open the box...

### ISSUE THREAD

**Issue by rayk** [hivedb/hive#450]
**Steps to Reproduce**
Problem is happening on the web platform.
1. Application startup is the first time the two boxes in question are created (1 Async & 1 Sync).
 - Box names contain a fixed prefix and a 9 char string (based on some id).
 - for example nod-f71f6ff8 & ent-f71f6ff8
2. If the boxes are empty they are populated with some with sample data. 
 - This works fine, and it's so fast.
 - After this point, we can read and write to the boxes no problems.
3. If the user refreshed the browser that is when **_HiveError: To use this list, you have to open the box "nod-f71f6ff8" first_** is thrown.

**Code sample**
1. TypeAdapters registered in main.
2. Code below is called before the material app
```dart
Future<EntityStore> entityStoreForNamespace(String nsUid, Clock clock) async {
  var name = 'ent-${nsUid.substring(0, 8)}';
  var box = Hive.isBoxOpen(name)
      ? Hive.lazyBox<Entity>(name)
      : await Hive.openLazyBox<Entity>(name).catchError(
          (e) => print('** catching -> HiveError: To use this list.. $e'));
  return EntityStore(
      asyncPersistor: AsyncPersistor<Entity>(
          hiveStore: box,
          onNotFoundBuilder: (key) => Entity.forFailedGet(key),
          serializers: primitiveSerializers),
      clock: clock);
}
```

and one for the sync box is pretty much the same.

```dart
Future<NodeStore> nodeStoreForNamespace(String nsUid, Clock clock) async {
  var name = 'nod-${nsUid.substring(0, 8)}';
  var box = Hive.isBoxOpen(name)
      ? Hive.box<Node>(name)
      : await Hive.openBox<Node>(name).catchError(
          (e) => print('** catching -> HiveError: To use this list.. $e'));
  return await NodeStore(
      syncStore: SyncPersistor<Node>(
          hiveStore: await box,
          onNotFoundBuilder: (key) => Node.forFailedGet(key)),
      clock: clock);
}

```
Both ```<Node>``` and ```<Entity>``` extend ```<HiveObject>```

The print statement is where it is caught and the site appears to be inside ```hive_list_impl.dart``` in particular the getting for the box [line 54](https://github.com/hivedb/hive/blob/9ce84d366590a6d324f7c34a035144b8fd66255d/hive/lib/src/object/hive_list_impl.dart#L54). As to why? I can not work it out.

1. Can confirm that both boxes are actually there in the browser. (Using chrome and not using incog mode).
2. Can confirm if I call ```Hive.boxExist``` the indexed exist and they are not open on the refresh 'As expected'.

_* Note this stack track is for the Sync box with called before the Async lazy box._

```stack
Error: HiveError: To use this list, you have to open the box "nod-f71f6ff8" first.
    at Object.throw_ [as throw] (http://localhost:50572/dart_sdk.js:4328:11)
    at HiveListImpl.lazy.get box [as box] (http://localhost:50572/packages/hive/src/box/lazy_box_impl.dart.lib.js:1913:23)
    at HiveListImpl.lazy.get delegate [as delegate] (http://localhost:50572/packages/hive/src/box/lazy_box_impl.dart.lib.js:1938:32)
    at HiveListImpl.lazy.cast (http://localhost:50572/packages/hive/src/util/delegating_list_view_mixin.dart.lib.js:84:21)
    at http://localhost:50572/packages/decdeck/model/state/graph/graph.dart.lib.js:751:93
    at graph.NodeAdapter.new.read (http://localhost:50572/packages/decdeck/model/state/graph/graph.dart.lib.js:756:9)
    at binary_reader_impl.BinaryReaderImpl.new.read (http://localhost:50572/packages/hive/src/box/lazy_box_impl.dart.lib.js:1501:35)
    at storage_backend_js.StorageBackendJs.new.decodeValue (http://localhost:50572/packages/hive/src/box/lazy_box_impl.dart.lib.js:1628:27)
    at MappedListIterable.new.elementAt (http://localhost:50572/dart_sdk.js:21541:25)
    at ListIterator.new.moveNext (http://localhost:50572/dart_sdk.js:21335:55)
    at JsIterator.next (http://localhost:50572/dart_sdk.js:5997:21)
    at storage_backend_js.StorageBackendJs.new.initialize (http://localhost:50572/packages/hive/src/box/lazy_box_impl.dart.lib.js:1685:20)
    at initialize.next (<anonymous>)
    at http://localhost:50572/dart_sdk.js:37593:33
    at _RootZone.runUnary (http://localhost:50572/dart_sdk.js:37447:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:50572/dart_sdk.js:32424:29)
    at handleValueCallback (http://localhost:50572/dart_sdk.js:32971:49)
    at Function._propagateToListeners (http://localhost:50572/dart_sdk.js:33009:17)
    at _Future.new.[_completeWithValue] (http://localhost:50572/dart_sdk.js:32852:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50572/dart_sdk.js:32874:35)
    at Object._microtaskLoop (http://localhost:50572/dart_sdk.js:37708:13)
    at _startMicrotaskLoop (http://localhost:50572/dart_sdk.js:37714:13)
    at http://localhost:50572/dart_sdk.js:33226:9

```

**Version**
 - Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-AU)
 -  hive: ^1.4.4

**Comment by TheMisir** [comment]
1. Does Entity depends on Node? I mean do they have any [relationship](https://docs.hivedb.dev/#/custom-objects/relationships) between?
2. In which order are you opening the boxes?

**Comment by rayk** [comment]
There is no relationship between the entity and the node, in that one has a hard dependence on the other. There is a temporal data dependence, in that after the entity is written to the async store and its ```id``` is returned that ```id``` is stored in the node sync box. Even in this code, there is never a cross over, the code that handles Node never reads or writes to the entity box.

**Comment by rayk** [comment]
Hi @TheMisir  & @leisim any thoughts on this one?

**Comment by TheMisir** [comment]
Sorry for the delay.

Can I see your hive models? (especially ones that uses HiveList).

I haven't figured out the reason yet.

**Comment by leisim** [comment]
First of all, thanks for this amazingly detailed bug description :+1:

I currently just have my phone but I believe the problem is the `.cast()` calls in your custom type adapter. You need to call `castHiveList()` we could not override the `cast()` method because of Darts type system.

But I believe we should override it and throw a meaningful error when it is called.

**Comment by leisim** [comment]
Thanks for this amazingly detailed bug description :+1:

Did you write the `TypeAdapter` yourself? Could you please share the model classes (`Node` and `Entity`)?

**Comment by TheMisir** [comment]
> First of all, thanks for this amazingly detailed bug description 👍
> 
> I currently just have my phone but I believe the problem is the `.cast()` calls in your custom type adapter. You need to call `castHiveList()` we could not override the `cast()` method because of Darts type system.
> 
> But I believe we should override it and throw a meaningful error when it is called.

Btw during debugging this issue I found out that `HiveLists` doesn't works with lazy boxes. Should I add a way to upgrade lazy box to regular box then read items or make sure `HiveList`s works with lazy boxes too (by lazily getting items).

What do you think about that @leisim?

**Comment by leisim** [comment]
> Should I add a way to upgrade lazy box to regular box then read items or make sure HiveLists works with lazy boxes too (by lazily getting items).

I don't think that would be a good idea. I made this choice in purpose. The user should choose to use a normal box over a lazy box (and the consequences like higher RAM usage) if he wants to use `HiveList`s. Implicitly converting to a normal box is a bad idea in my opinion.

**Comment by TheMisir** [comment]
> > Should I add a way to upgrade lazy box to regular box then read items or make sure HiveLists works with lazy boxes too (by lazily getting items).
> 
> I don't think that would be a good idea. I made this choice in purpose. The user should choose to use a normal box over a lazy box (and the consequences like higher RAM usage) if he wants to use `HiveList`s. Implicitly converting to a normal box is a bad idea in my opinion.

Ok. But what do you think about getting items lazily if box is lazy box instead of throwing "box is lazy" exception.

**Comment by rayk** [comment]
Hi @leisim & @TheMisir sorry about the slow response, below is the ```Node``` class. I shall have a look at the casting issue asap. Thanks again guys for looking to this.

```dart
class Node extends HiveObject {
  final bool _isFailedGet;
  final String _failedGetId;

  DateTime domObjExistedSince;

  String domObjType;

  String domObjUid;

  int entityKey;

  DateTime indexed;

  List<Node> incomingEdges;

  List<Node> outgoingEdges;

  DateTime updated;

  bool isAsymmetric;

  bool isFunctional;

  bool isInverseFunctional;

  bool isIrreflexive;

  bool isObject;

  bool isPredicate;

  bool isReflexive;

  bool isSubject;

  bool isSymmetric;

  bool isTransitive;

  Node()
      : _isFailedGet = false,
        _failedGetId = '0';
  factory Node.forFailedGet(dynamic key) {
    return Node._(true, key);
  }

  factory Node.forObject(DomainObject object, DateTime timestamp) {
    return Node()
      ..indexed = timestamp
      ..rev = 0
      ..domObjUid = object.uid
      ..domObjType = object.formalTypeName
      ..isSubject = false
      ..isPredicate = false
      ..isObject = true
      ..isAsymmetric = false
      ..isFunctional = false
      ..isInverseFunctional = false
      ..isIrreflexive = false
      ..isReflexive = false
      ..isSymmetric = false
      ..isTransitive = false;
  }

  factory Node.forPredicate(DomainPredicate predicate, DateTime timestamp) {
    var n = Node()
      ..indexed = timestamp
      ..rev = 0
      ..domObjUid = predicate.uid
      ..domObjType = predicate.formalTypeName
      ..isSubject = false
      ..isPredicate = true
      ..isObject = false
      ..isAsymmetric = predicate is Asymmetric
      ..isFunctional = predicate is Functional
      ..isInverseFunctional = predicate is InverseFunctional
      ..isIrreflexive = predicate is Irreflexive
      ..isReflexive = predicate is Reflexive
      ..isSymmetric = predicate is Symmetric
      ..isTransitive = predicate is Transitive;

    return n;
  }

  factory Node.forSubject(DomainObject subject, DateTime timestamp) {
    final sn = Node()
      ..indexed = timestamp
      ..rev = 0
      ..domObjUid = subject.uid
      ..domObjType = subject.formalTypeName
      ..isSubject = true
      ..isObject = false
      ..isPredicate = false
      ..isAsymmetric = false
      ..isFunctional = false
      ..isInverseFunctional = false
      ..isIrreflexive = false
      ..isReflexive = false
      ..isSymmetric = false
      ..isTransitive = false;

    return sn;
  }

  Node._(bool isFailGet, String failId)
      : _isFailedGet = isFailGet,
        _failedGetId = failId ?? '0',
        isPredicate = false,
        isSubject = false,
        rev = 0;

  String get failToGetKey => _failedGetId;

  @override
  int get hashCode => hash8(domObjUid, domObjType, domObjExistedSince,
      entityKey, indexed, incomingEdges, outgoingEdges, updated);

  bool get isFailedGet => _isFailedGet;

  @override

  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Node &&
          runtimeType == other.runtimeType &&
          domObjExistedSince == other.domObjExistedSince &&
          entityKey == other.entityKey &&
          domObjType == other.domObjType &&
          domObjUid == other.domObjUid &&
          indexed == other.indexed;

  Node addIncomingEdge(Node inNode, DateTime timestamp) {
    if (!incomingEdges.contains(inNode)) {
      incomingEdges.add(inNode);
      updated = timestamp;
      rev = rev++;
    }
    return this;
  }

  Node addOutgoingEdge(Node outNode, DateTime timestamp) {
    if (!outgoingEdges.contains(outNode)) {
      outgoingEdges.add(outNode);
      updated = timestamp;
      rev = rev++;
    }
    return this;
  }

  Node linkTo(Entity ent) {
    assert(ent.key != null);
    entityKey = ent.key;
    rev = rev++;
    return this;
  }

  @override
  String toString() {
    var sb = StringBuffer(
        '\n** Node -> <$domObjType> uid: $domObjUid ${isInBox ? 'entity-key: $entityKey' : 'Not yet persisted!'} **\n');
    sb.writeln('*\t - revision: $rev');
    sb.writeln('*\t - inStore:\t $isInBox');
    sb.writeln('*\t - indexed:\t $indexed');
    sb.writeln('*\t - updated:\t $updated');
    sb.writeln('*\t - isSubject:\t $isSubject');
    sb.writeln('*\t - isPredicate:\t $isPredicate');
    sb.writeln('*\t - isObject:\t $isObject');

    if (isPredicate) {
      sb.writeln('*\t - predicate: ');
      if (isFunctional) sb.writeln('*\t\t| isFunctional');
      if (isInverseFunctional) sb.writeln('*\t\t| isInverseFunctional');
      if (isSymmetric) sb.writeln('*\t\t| isSymmetrical');
      if (isAsymmetric) sb.writeln('*\t\t| isAsymmetrical');
      if (isTransitive) sb.writeln('*\t\t| isTransitive');
      if (isReflexive) sb.writeln('*\t\t| isReflexive');
      if (isIrreflexive) sb.writeln('*\t\t| isIrreflexive');
    }

    sb.writeln('*\t - incoming:');
    if (incomingEdges != null && incomingEdges.isNotEmpty) {
      for (var i in incomingEdges) {
        sb.writeln(
            '*\t\t| ${incomingEdges.indexOf(i)} - <${i.domObjType}> uid: ${i.domObjUid} asOf: ${i.indexed}');
      }
    } else {
      sb.writeln('*\t\t| None');
    }

    sb.writeln('*\t - outgoing:');
    if (outgoingEdges != null && outgoingEdges.isNotEmpty) {
      for (var o in outgoingEdges) {
        sb.writeln(
            '*\t\t| ${outgoingEdges.indexOf(o)} - <${o.domObjType}> uid: ${o.domObjUid} asOf: ${o.indexed}');
      }
    } else {
      sb.writeln('*\t\t| None');
    }

    return sb.toString();
  }
}
```

Here is the entity..

```dart
class Entity extends HiveObject {
  /// Flag when this entity was created as a result of failing to get a key from store.
  final bool _isResultOfFailedGet;

  /// The key the caused the fail.
  final int _failedGetKey;

  /// Contain the primitive serialization of a Persistable Object.
  List<Object> payload;

  /// Returns true if this entity does not have a payload.
  bool get isEmpty => payload == null || payload.isEmpty;

  /// Returns true if this entity was created as a result of a failed get.
  bool get isFail => _isResultOfFailedGet;

  /// Returns the key value that resulted in the failure.
  dynamic get failedKey => _failedGetKey;

  /// Default constructor for creation from the serialised form.
  Entity()
      : _isResultOfFailedGet = false,
        _failedGetKey = 0;

  Entity._(this._isResultOfFailedGet, this._failedGetKey);

  factory Entity.forFailedGet(dynamic key) {
    return (Entity._(true, key));
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Entity &&
          runtimeType == other.runtimeType &&
          _isResultOfFailedGet == other._isResultOfFailedGet &&
          _failedGetKey == other._failedGetKey &&
          payload == other.payload;

  @override
  int get hashCode =>
      _isResultOfFailedGet.hashCode ^ _failedGetKey.hashCode ^ payload.hashCode;

  @override
  String toString() {
    var sb = StringBuffer();
    sb.writeln('** Entity **');
    sb.writeln('*\t - Entity Key: $key');
    sb.writeln('*\t - Persisted: $isInBox');
    sb.writeln(
        '*\t - Represents Failure: ${_isResultOfFailedGet ? 'True : $_failedGetKey' : 'False'}');

    if (payload != null && payload.isNotEmpty) {
      sb.writeln('*\t - Payload:');
      for (var v in payload) {
        sb.writeln('* \t\t | ${payload.indexOf(v)} : $v');
      }
    } else {
      sb.writeln('*\t - Payload: None');
    }

    return sb.toString();
  }
}
```
