### ISSUE TITLE
Hive crashes at start

### ISSUE THREAD

**Issue by AlexBacich** [hivedb/hive#516]
**Steps to Reproduce**
Starting the app at some point brings this crash stack. After cleaning Hive (reinstalling or using another box) error goes away. 

**Code sample**
```
flutter: #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:17:26)
flutter: #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:41:12)
flutter: <asynchronous suspension>
flutter: #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:82:30)
flutter: <asynchronous suspension>
flutter: #4      BoxBaseImpl.initialize (package:hive/src/box/box_base_impl.dart:90:20)
flutter: #5      HiveImpl._openBox (package:hive/src/hive_impl.dart:106:22)
flutter: <asynchronous suspension>
flutter: #6      HiveImpl.openBox (package:hive/src/hive_impl.dart:135:18)
flutter: #7      Preferences.init (package:iceflutter/model/storage/preferences.dart:60:16)
flutter: <asynchronous suspension>
flutter: #8      main.<anonymous closure> (package:iceflutter/main.dart:19:25)
flutter: #9      _rootRun (dart:async/zone.dart:1190:13)
flutter: #10     _CustomZone.run (dart:async/zone.dart:1093:19)
flutter: #11     _runZoned (dart:async/zone.dart:1630:10)
flutter: #12     runZonedGuarded (dart:async/zone.dart:1618:12)
flutter: #13     main (package:iceflutter/main.dart:18:3)
flutter: #14     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
flutter: #15     _rootRun (dart:async/zone.dart:1190:13)
flutter: #16     _CustomZone.run (dart:async/zone.dart:1093:19)
flutter: #17     _runZoned (dart:async/zone.dart:1630:10)
flutter: #18     runZonedGuarded (dart:async/zone.dart:1618:12)
flutter: #19     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
flutter: #20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
flutter: #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

**Version**
 - Platform: iOS, 
 - Flutter version: [1.22.4,]
 - Hive version: [^1.4.4+1]

**Comment by AlexBacich** [comment]
Looks like duplicate of https://github.com/hivedb/hive/issues/263
