### ISSUE TITLE
Map<String,dynamic> from Hive doesn't behave like a proper Map<String,dynamic>

### ISSUE THREAD

**Issue by moseskarunia** [hivedb/hive#522]
**Version**
 - Platform: iOS, Android
 - Flutter version: 1.22.3
 - Hive version: 1.4.4
 - Flutter Hive version: 0.3.1

Hello guys, so I'm facing a difficulty understanding what type of Map does Hive returns. Below is my code:

**Code sample**
```dart
Future<List<Map<String, dynamic>>> readFromHive() async {
  final box = await Hive.openBox('storageName');
  final result = box.toMap().map(
        (k, e) => MapEntry(
          k.toString(),
          Map<String, dynamic>.from(e),
        ),
      );

  return result.values.toList();

  /// Let's say the result is:
  /// ```
  /// [ { name: 'John Doe', email: 'johndoe@gmail.com'} ]
  /// ```
}

final results = await readFromHive();

print(results[0]); // { name: John Doe, email: johndoe@gmail.com}
print(results[0]['name']); // null
print(results[0]['email']); // null
print(results[0].runtimeType) // _InternalLinkedHashMap<String, dynamic>
```

Here's the weird things:
1. If it's not a `Map<String,dynamic>` why doesn't it crash the moment it exits the `readFromHive()`?
2. If it's a `Map<String,dynamic>` why does `print(results[0]['name']);` prints null, while `print(results[0])` prints correct result?
3. I actually uses `@JsonSerializable` package. And I always need to pass `anyMap: true` in order for the `fromJson` to work properly. I never feels to pass `anyMap: true` if I don't deal with Hive.
4. I use VS Code, and I put a breakpoint on the print statement. When I inspect the type of `results[0]`, the type truly says `Map<String,dynamic>`

So, the question is like the title, why does it feels like Hive Map<String,dynamic> is not really acts like a Map<String,dynamic>? And how to make it a "true" `Map<String,dynamic>? Or is this intended? Maybe I misunderstand how Hive works?

Thanks

P.S. I can't use Hive's built in json parser since in a clean architecture, the entity and data source should not even care which local storage library I use.

**Comment by TheMisir** [comment]
Why you're not using `Hive.box(..).values`?

```dart
Future<List<Map<String, dynamic>>> readFromHive() async {
  final box = await Hive.openBox('storageName');
  final result = box.values.cast<Map<String, dynamic>>();
  return result;

  /// Let's say the result is:
  /// ```
  /// [ { name: 'John Doe', email: 'johndoe@gmail.com'} ]
  /// ```
}
```

**Comment by moseskarunia** [comment]
> ```dart
> box.values.cast<Map<String, dynamic>>()
> ```

Hi, thanks for the response @TheMisir , it worked. Thanks.

**Comment by moseskarunia** [comment]
@TheMisir turns out crashes on the real usage (succeed on test)

```dart
try {
  final box = await hive.openBox(storageName);
  return box.values.cast<Map<String, dynamic>>().toList(); // crashes here
catch (e) {
  throw CleanException(name: 'UNEXPECTED_ERROR', group: 'hive'); // Got here
}
```
    
Error
> _CastError (type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast)

**Comment by jrcodev** [comment]
I'm facing the same issue, I'm using box.values.toList(), but every time a exception is throwing: 
`_CastError (type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast)`

**Comment by jrcodev** [comment]
@moseskarunia I used your workaround, but the error persists. Seems that the error is in hive toMap function from BoxImpl, this is my call stack:

BoxImpl.toMap (/home/jrcodev/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/hive-1.4.4+1/lib/src/box/box_impl.dart:102)
StorageDatasourceImp.getLinks (/home/jrcodev/Documentos/Projects/Mobile/Doggi/doggi/lib/modules/app/external/datasources/storage_datasource_imp.dart:29)
<asynchronous gap> (Unknown Source:0)
AppRepository.getAllLinks (/home/jrcodev/Documentos/Projects/Mobile/Doggi/doggi/lib/modules/core/data/repositories/app_repository.dart:15)
GetLinks.call (/home/jrcodev/Documentos/Projects/Mobile/Doggi/doggi/lib/modules/core/interactors/get_links.dart:9)
_HomeWidgetState.build.<anonymous closure> (/home/jrcodev/Documentos/Projects/Mobile/Doggi/doggi/lib/modules/app/presentation/home/home_widget.dart:43)
Consumer.buildWithChild (/home/jrcodev/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.3.2+3/lib/src/consumer.dart:177)
SingleChildStatelessWidget.build (/home/jrcodev/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/nested-0.0.4/lib/nested.dart:260)
StatelessElement.build (/home/jrcodev/Flutter/flutter/packages/flutter/lib/src/widgets/framework.dart:4701)
SingleChildStatelessElement.build (/home/jrcodev/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/nested-0.0.4/lib/nested.dart:280)

I removed the most part of my call stack for obvious reasons, but this error has nothing to do with my code. 
I'm not using type adapter, only the default types supported by hive. The error ever occurs when box.values is called, other operations works as well.

**Comment by Harrys76** [comment]
> @TheMisir turns out crashes on the real usage (succeed on test)
> 
> ```dart
> try {
>   final box = await hive.openBox(storageName);
>   return box.values.cast<Map<String, dynamic>>().toList(); // crashes here
> catch (e) {
>   throw CleanException(name: 'UNEXPECTED_ERROR', group: 'hive'); // Got here
> }
> ```
> 
> Error
> 
> > _CastError (type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast)
> 
> However, this works
> 
> ```dart
> final box = await hive.openBox(storageName);
> final result = box.toMap().map(
>   (k, e) => MapEntry(
>     k.toString(),
>     Map<String, dynamic>.from(e),
>   ),
> );
> 
> return result.values.toList();
> ```

still got error `type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast`

**Comment by moseskarunia** [comment]
@Harrys76 

I'm currently using this with a package named freezed and it seems to work seamlessly.

**Comment by TheMisir** [comment]
@Harrys76 due to dart's type system limitations, Hive can not persist generic types. Instead of Map<String, dynamic> hive returns Map<dynamic, dynamic> so you have to cast it manually.

**Comment by Harrys76** [comment]
@moseskarunia @TheMisir could you help me to solve it?

I sometimes got 'subtype of type' error when run this code

```dart
Stream<List<Map<String,` dynamic>>> watchList(T dataSource) async* {
    final _box = await _openBox(dataSource);
    yield* _box.watch().map((event) => _box.values.toList());
  }
  ```
  the error occur in `_box.values.toList()`

**Comment by moseskarunia** [comment]
> @moseskarunia @TheMisir could you help me to solve it?
> 
> I sometimes got 'subtype of type' error when run this code
> 
> ```dart
> Stream<List<Map<String,` dynamic>>> watchList(T dataSource) async* {
>     final _box = await _openBox(dataSource);
>     yield* _box.watch().map((event) => _box.values.toList());
>   }
>   ```
>   the error occur in `_box.values.toList()`

Parse the map object with freezed first to produce a new sane list of dart object. Don't access it directly.

**Comment by Harrys76** [comment]
@moseskarunia 

i tried two things:
1. make a freezed class and parse the value from `_box.values` like this:
```dart
Stream<List<BoxRecords>> watchList(T dataSource) async* {
    final _box = await _openBox(dataSource);
    yield* _box.watch().map((event) => _box.values.map((value) => BoxRecords(records: value)).toList());
  }
  ```
  
 2. use BoxRecords as TypeAdapter
 ```dart
Stream<List<BoxRecords>> watchList(T dataSource) async* {
    final _box = await _openBox(dataSource);
    yield* _box.watch().map((event) => _box.values.toList());
  }
  ```
  
  still got this error:
```  
/flutter (27820): type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'BoxRecords' in type cast
I/flutter (27820): 
I/flutter (27820): #0      Keystore.getValues.<anonymous closure> (package:hive/src/box/keystore.dart:122:45)
I/flutter (27820): #1      MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
I/flutter (27820): #2      new List.from (dart:core-patch/array_patch.dart:50:19)
I/flutter (27820): #3      new List.of (dart:core-patch/array_patch.dart:68:17)
I/flutter (27820): #4      Iterable.toList (dart:core/iterable.dart:404:12)
I/flutter (27820): #5      DataSourceRecordBox.watchList.<anonymous closure> (package:jojotask/src/repositories/cache/hive/box/form_record_box.dart:35:52)
I/flutter (27820): #6      _MapStream._handleData (dart:async/stream_pipe.dart:219:31)
I/flutter (27820): #7      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
I/flutter (27820): #8      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter (27820): #9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter (27820): #10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
I/flutter (27820): #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
I/flutter (27820): #12     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
I/flutter (27820): #13     _StreamImplEvents.handleNext (dart:async/stream_impl
```

**Comment by moseskarunia** [comment]
@Harrys76 you have to parse it using the freezed class's fromJson function. (annotate your factory using @JsonSerializable, with at least - both of anyMap and checked set to true. That's what makes it work in my case.

**Comment by Harrys76** [comment]
thank you @moseskarunia for pointing out a solution. Parsing with `fromJson()` from freezed class is works. I already try to reproduce the error by kill app and open it again, the error gone.

so in my case, I'm using `BoxRecords` class as TypeAdapter and this is my `BoxRecordsAdapter` class:

```dart
class BoxRecordsAdapter extends TypeAdapter<BoxRecords> {
  @override
  final typeId = 0;

  @override
  BoxRecords read(BinaryReader reader) {
    final result = Map<String, dynamic>.from(reader.read());
    return BoxRecords.fromJson({'records': result});
  }

  @override
  void write(BinaryWriter writer, BoxRecords obj) {
    writer.write<Map<String, dynamic>>(obj.records);
  }
}
```

**Comment by moseskarunia** [comment]
@TheMisir with all due respect, solving it using other library doesn't solve the actual problem within the library itself. Therefore, I'm reopening it.

**Comment by rokk4** [comment]
I had similar problems, we have a LOT of DTO Classes, many of them are deeply nested and also Unions generated with freezed.  
What works for me is that I use the .to/fromJson() of the classes wrap them with a Class that has a generated TypeAdapter.
Directly using the Map<String,dynamic> of .to/fromJson() with a `Box<Map<String, dynamic>>`  or `Box<Map<String, dynamic>?>` produced the "not a subtype errors", AFTER restart. Also the suggested cast() etc. did not work for me.

This works for me:
```dart
 Box<DtoJsonHiveWrapper> _box = await Hive.openBox(
      "box",
      encryptionCipher: HiveAesCipher(encryptionKey),
    );
```

```dart
import 'package:hive_flutter/hive_flutter.dart';

part 'dto_hive_wrapper.g.dart';

@HiveType(typeId: 7)
class DtoJsonHiveWrapper {
  @HiveField(0)
  final Map<String, dynamic> dtoJson;

  DtoJsonHiveWrapper({required this.dtoJson});
}
```

```
[✓] Flutter (Channel beta, 2.5.0-5.2.pre, on macOS 11.5.1 20G80 darwin-arm, locale en-DE)
    • Flutter version 2.5.0-5.2.pre at /Users/r0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 19c61fed0d (12 days ago), 2021-08-18 17:10:31 -0700
    • Engine revision 7a4c4505f6
    • Dart version 2.14.0 (build 2.14.0-377.7.beta)

```

**Comment by logic-and-math** [comment]
@rokk4 This solution doesn't work for nested classes in my case.

**Comment by Nico04** [comment]
I have just setup Hive, I'm having the same issue here.
I'm storing Map<String, dynamic> in the box, but I've got a cast exception when reading values.

**Comment by pckimlong** [comment]
For me I can't found any solution rather than doing quick fix jsonEncode then decode it back. This worked for me even I have nested map inside map, But performance is my concern.

```
Map<String, dynamic> _parser(dynamic hiveMap){
  final jsonString = jsonEncode(hiveMap);
  return jsonDecode(jsonString);
}
```

```
Future<AppSetting?> getAppSetting() async {
    try {
      final result = await _box.get(_appSetting);
      if (result == null) return null;
      return AppSetting.fromJson(_parser(result));
    } on Exception catch (e) {
      debugPrint(e.toString());
      return null;
    }
  }
```

**Comment by pedropacheco92** [comment]
I've added a custom type adapter that worked for me, in nested Map structures.
I generated a adapter and just extended it and overrode the read method for this:

`@override
  FooBar read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };

    return FooBar(
      fields[0] as String,
      _castInternalMap(fields[1]), // changed just this
    );
  }

  dynamic _castInternalMap(dynamic value) {
    if (value != null && value is Map) {
      return value.cast<String, dynamic>().map(
            (key, value) => MapEntry(key, _castInternalMap(value)),
          );
    }
    return value;
  }`

The `_castInternalMap` will check the value and handle it recursively
