### ISSUE TITLE
Unhandled Exception: HiveError: Cannot read, unknown typeId: 33. Did you forget to register an adapter?

### ISSUE THREAD

**Issue by Fmaldonado6** [hivedb/hive#580]
**Steps to Reproduce**
This issue occurred to me when I updated my app with a new field on the database, old fields were the same I just added a new one. It only happens if you update the app and you had data saved.

**Code sample**

Model with old field
```
@JsonSerializable()
@HiveType(typeId: 0)
class SavedCharacter {
  @HiveField(0)
  final int characterId;
  @HiveField(1)
  final String imageUrl;
  @HiveField(2)
  final String name;

  SavedCharacter({
    this.characterId,
    this.imageUrl,
    this.name,
  });
  factory SavedCharacter.fromJson(Map<String, dynamic> json) =>
      _$SavedCharacterFromJson(json);
  Map<String, dynamic> toJson() => _$SavedCharacterToJson(this);
}
```

Model with new field
```
@JsonSerializable()
@HiveType(typeId: 0)
class SavedCharacter {
  @HiveField(0)
  final int characterId;
  @HiveField(1)
  final String imageUrl;
  @HiveField(2)
  final String name;
  @HiveField(3)
  final String date;

  SavedCharacter({
    this.characterId,
    this.imageUrl,
    this.name,
    this.date,
  });
  factory SavedCharacter.fromJson(Map<String, dynamic> json) =>
      _$SavedCharacterFromJson(json);
  Map<String, dynamic> toJson() => _$SavedCharacterToJson(this);
}
```

Main function where Hive is initiated

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final appDocumentDirectory = await getApplicationDocumentsDirectory();
  Hive.init(appDocumentDirectory.path);
  Hive.registerAdapter(SavedCharacterAdapter());
  runApp(
    MyApp(),
  );
}
```
**Full error**
```
2021-03-02 08:39:38.766 13238-14071/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HiveError: Cannot read, unknown typeId: 33. Did you forget to register an adapter?
    #0      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:322)
    #1      SavedCharacterAdapter.read (package:random_waifu/models/models.g.dart:17)
    #2      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:325)
    #3      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:273)
    #4      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:17)
    #5      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:41)
    <asynchronous suspension>
    #6      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:82)
    <asynchronous suspension>
    #7      HiveImpl._openBox (package:hive/src/hive_impl.dart:106)
    <asynchronous suspension>
    #8      HiveImpl.openBox (package:hive/src/hive_impl.dart:135)
    <asynchronous suspension>
    #9      DatabaseRepository.init (package:random_waifu/repositories/local_database_repository.dart:9)
    <asynchronous suspension>
    #10     HomeCubit.getRandomWaifu (package:random_waifu/screens/home/cubit/home_cubit.dart:38)
    <asynchronous suspension>
2021-03-02 08:39:38.766 13238-14071/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HiveError: Cannot read, unknown typeId: 33. Did you forget to register an adapter?
    #0      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:322)
    #1      SavedCharacterAdapter.read (package:random_waifu/models/models.g.dart:17)
    #2      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:325)
    #3      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:273)
    #4      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:17)
    #5      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:41)
    <asynchronous suspension>
    #6      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:82)
    <asynchronous suspension>
    #7      HiveImpl._openBox (package:hive/src/hive_impl.dart:106)
    <asynchronous suspension>
    #8      HiveImpl.openBox (package:hive/src/hive_impl.dart:135)
    <asynchronous suspension>
    #9      DatabaseRepository.init (package:random_waifu/repositories/local_database_repository.dart:9)
    <asynchronous suspension>
    #10     HomeCubit.getRandomWaifu (package:random_waifu/screens/home/cubit/home_cubit.dart:38)
```

**Version**
 - Platform:  Android
 - Flutter version: 1.22.4
 - Hive version: 1.4.4

**Comment by Fmaldonado6** [comment]
Sorry guys, it seems that in my previous version I was saving some classes that were no longer needing, so hive tried to read them and it failed as there was no longes an adapter registered
