### ISSUE TITLE
Using hive for web: "Invalid argument(s): Invalid or corrupted pad block" on refresh browser

### ISSUE THREAD

**Issue by BenPoell** [hivedb/hive#652]
**Steps to Reproduce**
Here is a repository to reproduce the issue:
https://github.com/BenPoell/hive_reproduce

Following setting:
- using named routes for navigation
- storing the **encrypted hive box** in a Flavor
- init the hive box in main
- navigate from the start screen to another route
- set the value in the box on the second route
- (navigate back and forth)
- refresh the browser

On reload the error `Invalid argument(s): Invalid or corrupted pad block"` occurs

**Stack trace**
```
Error: Invalid argument(s): Invalid or corrupted pad block
    at Object.throw_ [as throw] (http://localhost:61171/dart_sdk.js:5333:11)
    at aes_cbc_pkcs7.AesCbcPkcs7.new.decrypt (http://localhost:61171/packages/hive/src/crypto/aes_cbc_pkcs7.dart.lib.js:133:21)
    at hive.HiveAesCipher.new.decrypt (http://localhost:61171/packages/hive/src/box/lazy_box_impl.dart.lib.js:3829:28)
    at binary_reader_impl.BinaryReaderImpl.new.readEncrypted (http://localhost:61171/packages/hive/src/box/lazy_box_impl.dart.lib.js:1684:30)
    at storage_backend_js.StorageBackendJs.new.decodeValue (http://localhost:61171/packages/hive/src/box/lazy_box_impl.dart.lib.js:1809:27)
    at MappedListIterable.new.elementAt (http://localhost:61171/dart_sdk.js:22725:25)
    at ListIterator.new.moveNext (http://localhost:61171/dart_sdk.js:22520:55)
    at JsIterator.next (http://localhost:61171/dart_sdk.js:7057:21)
    at storage_backend_js.StorageBackendJs.new.initialize (http://localhost:61171/packages/hive/src/box/lazy_box_impl.dart.lib.js:1881:20)
    at initialize.next (<anonymous>)
    at http://localhost:61171/dart_sdk.js:39031:33
    at _RootZone.runUnary (http://localhost:61171/dart_sdk.js:38888:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:61171/dart_sdk.js:33874:29)
    at handleValueCallback (http://localhost:61171/dart_sdk.js:34434:49)
    at Function._propagateToListeners (http://localhost:61171/dart_sdk.js:34472:17)
    at _Future.new.[_completeWithValue] (http://localhost:61171/dart_sdk.js:34314:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:61171/dart_sdk.js:34337:35)
    at Object._microtaskLoop (http://localhost:61171/dart_sdk.js:39175:13)
    at _startMicrotaskLoop (http://localhost:61171/dart_sdk.js:39181:13)
    at http://localhost:61171/dart_sdk.js:34688:9
```

**Version**
 - Platform: Web
 - Flutter version: 2.0.4
 - Hive version: 2.0.4

**Comment by aquilarafa** [comment]
For me it was happening even on first run. Fixed when updated hive to 2.0.5, clean chrome cache and did a **flutter clean**.

**Comment by agordeev** [comment]
This happens on hive 2.2.3 too.
I experience this on mobile Safari so far.

<img width="705" alt="Screenshot 2023-10-07 at 11 41 56" src="https://github.com/isar/hive/assets/2883524/ba4c9d4b-8998-4095-a89d-342159ced1a6">

**Comment by valtbarbos** [comment]
Same error here. For now, I am using this `recoveryOperation` approach:

```
final HiveInterface _storage;
await HiveInterface.deleteBoxFromDisk(hiveBoxName);
```

When "Invalid argument(s): Invalid or corrupted pad block" occurs, I just delete the box and try the operation again. It's not so good, but for my scenario, it solves for now.
