### ISSUE TITLE
FileSystemException: Cannot create file, path = '//testbox.hive' (OS Error: Read-only file system, errno = 30)

### ISSUE THREAD

**Issue by good-good-study** [hivedb/hive#656]
Flutter Hive version:2.0.4,  I download the Demo hivedb/hive ,  found abnormal after running :

Syncing files to device iPhone 12 Pro Max...
Restarted application in 840ms.

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: FileSystemException: Cannot create file, path = '//testbox.hive' (OS Error: Read-only file system, errno = 30)
#0      _File.create.<anonymous closure> (dart:io/file_impl.dart:255:9)
#1      _rootRunUnary (dart:async/zone.dart:1362:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
<asynchronous suspension>
#3      BackendManager.findHiveFileAndCleanUp (package:hive/src/backend/vm/backend_manager.dart:47:7)
<asynchronous suspension>
#4      BackendManager.open (package:hive/src/backend/vm/backend_manager.dart:24:16)
<asynchronous suspension>
#5      HiveImpl._openBox (package:hive/src/hive_impl.dart:100:15)
<asynchronous suspension>
#6      HiveImpl.openBox (package:hive/src/hive_impl.dart:139:12)
<asynchronous suspension>
#7      main (package:example/main.dart:32:13)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: FileSystemException: Cannot create file, path = '//testbox.hive' (OS Error: Read-only file system, errno = 30)
#0      _File.create.<anonymous closure> (dart:io/file_impl.dart:255:9)
#1      _rootRunUnary (dart:async/zone.dart:1362:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
<asynchronous suspension>
#3      BackendManager.findHiveFileAndCleanUp (package:hive/src/backend/vm/backend_manager.dart:47:7)
<asynchronous suspension>
#4      BackendManager.open (package:hive/src/backend/vm/backend_manager.dart:24:16)
<asynchronous suspension>
#5      HiveImpl._openBox (package:hive/src/hive_impl.dart:100:15)
<asynchronous suspension>
#6      HiveImpl.openBox (package:hive/src/hive_impl.dart:139:12)
<asynchronous suspension>
#7      main (package:example/main.dart:32:13)
<asynchronous suspension>
```

**Comment by TheMisir** [comment]
The example project inside `hive/example` is a simple dart application not flutter. You can simply run it using `dart main.dart`.

**Comment by bueltan** [comment]
I have to admit I feel a bit silly now, haha

**Comment by aneesshameed** [comment]
For Flutter use
```
final directory = await getApplicationDocumentsDirectory();
await Hive.initFlutter(directory.path);
```

Of course, you need to 
import 'package:path_provider/path_provider.dart';

**Comment by Adminixtrator** [comment]
> For Flutter use
> 
> ```
> final directory = await getApplicationDocumentsDirectory();
> await Hive.initFlutter(directory.path);
> ```
> 
> Of course, you need to import 'package:path_provider/path_provider.dart';

I made some modifications and this does it.
`WidgetsFlutterBinding.ensureInitialized();
final directory = await getApplicationDocumentsDirectory();
await Hive.initFlutter(directory.path);
`

**Comment by gronka** [comment]
To fix this error, I had to uninstall my flutter app from the Android device, then reinstall with `flutter run`

**Comment by chaudharydeepanshu** [comment]
For me, it was due to forgetting to provide the path when opening the database which was used when initializing Hive.

```dart
  Future openDb() async {
    Directory directory = await getApplicationDocumentsDirectory();        //<-----
    collection = await BoxCollection.open(
      'Collection',
      {'Box'},
      path: directory.path,  //<-----
    );
  }
```
