### ISSUE TITLE
Data type stored in Box is not recognized after reopening that box in a new session

### ISSUE THREAD

**Issue by warcayac** [hivedb/hive#753]
## Steps to Reproduce

This code works fine, and the `mapbox.hive` and `mapbox.lock` files are created successfully.

```
class HiveService {
  void initialize() async {
    print('Initializing Hive...');
    Hive.init('./hive_boxes');
  }

  FutureOr<void> runMapBox() async {
    var box = await Hive.openBox<Map<String, String>>('mapBox');
    
    await box.put('anyval', {'k1': '123'});
    await box.put(455, {'k1': 'aa', 'k2': '-23.89'});
    
    var keys = box.keys.toList();
    var values = box.values.toList();

    print('${keys.runtimeType} :: $keys');
    print('${values.runtimeType} :: $values');

    var data = box.get(455);
    print('Data recovered: $data');
  }

  void terminate() async {
    print('Closing boxes...');
  }
}

void main(List<String> arguments) async {
  var h = HiveService()..initialize();
  await h.runMapBox();
  h.terminate();
  print('\nJob done.');
}
```

But if I try to run the program again with this code:

```
class HiveService {
  void initialize() async {
    print('Initializing Hive...');
    Hive.init('./hive_boxes');
  }

  FutureOr<void> runMapBox() async {
    var box = await Hive.openBox<Map<String, String>>('mapBox');
    
    var data = box.get(455);
    print('Data recovered: $data');
  }

  void terminate() async {
    print('Closing boxes...');
  }
}

void main(List<String> arguments) async {
  var h = HiveService()..initialize();
  await h.runMapBox();
  h.terminate();
  print('\nJob done.');
}
```
I get this error message:

```
Initializing Hive...
Unhandled exception:
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, String>?' in type cast
#0      BoxImpl.get (package:hive/src/box/box_impl.dart:44:26)
#1      HiveService.runMapBox (file:///home/warcayac/Projects/dart/using_hive/bin/using_hive.dart:56:20)
<asynchronous suspension>
#2      main (file:///home/warcayac/Projects/dart/using_hive/bin/using_hive.dart:70:3)
<asynchronous suspension>
```

I tried with `box.get(455).cast<String, String>()`, and same error.

## Version

 - Platform: Manjaro Linux x86_64, kernel 5.13.5-1-MANJARO
 - Flutter version: 2.2.3
 - Hive version: 2.0.4

**Comment by mbaumgartenbr** [comment]
Hey!

Hive doesn't work with typed collections, you should use:

```dart
final box = await Hive.openBox<Map>('box');

final stored = await box.get('map'); // ?? <String, String>{};

// You must check for null, because `box.get()` can return null if the value is not in the box.
if (stored != null) {
  final map = Map<String, String>.from(stored);

  // Or
  final map = stored.cast<String, String>();
}

// Or simply
final Map<String, String> map = ((await box.get('map')) as Map?)?.cast<String, String>() ?? {};
```

I'm not sure if that's your issue, but give it a try.

**Comment by warcayac** [comment]
Thanks for the clarification.
