### ISSUE TITLE
ERROR:flutter/lib/ui/ui_dart_state.cc(209) Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.

### ISSUE THREAD

**Issue by pashtetbezd** [hivedb/hive#757]
`E/flutter ( 7765): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
E/flutter ( 7765): #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250:7)
E/flutter ( 7765): #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21:26)
E/flutter ( 7765): #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42:12)
E/flutter ( 7765): <asynchronous suspension>
E/flutter ( 7765): #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86:11)
E/flutter ( 7765): <asynchronous suspension>
E/flutter ( 7765): #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:116:9)
E/flutter ( 7765): <asynchronous suspension>
E/flutter ( 7765): #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:145:12)
E/flutter ( 7765): <asynchronous suspension>
E/flutter ( 7765): #6      main (package:miracle/main.dart:146:3)
E/flutter ( 7765): <asynchronous suspension>
E/flutter ( 7765): 
`

**Comment by cspensky** [comment]
I'm seeing this as well.  Are you by chance using callbacks in different Isolates to access Hive?

**Comment by ronpetit** [comment]
@cspensky I'm having this problem too, and yes, I'm using isolates callbacks to access Hive, more specifically the FirebaseBackgroundMessageHandler

**Comment by Rexios80** [comment]
Isolate support has been pre-released for `hive_ce`!

Get the pre-releases here:

[hive_ce](https://pub.dev/packages/hive_ce/versions/2.11.0-pre.4)
[hive_ce_flutter](https://pub.dev/packages/hive_ce_flutter/versions/2.3.0-pre.1)
[hive_ce_generator](https://pub.dev/packages/hive_ce_generator/versions/1.9.0-pre.1)

Please try out `IsolatedHive` in your projects and report any issues you may have. I want to make sure all potential issues are ironed out before I make a real release.
