### ISSUE TITLE
Concurrency model - accessing boxes from multiple isolates?

### ISSUE THREAD

**Issue by daniel-v** [hivedb/hive#77]
**Steps to Reproduce**
Run the code sample.

**Code sample**
```dart
import 'dart:isolate';

import 'package:hive/hive.dart';

enum WriteType { num, alpha }

const writeCount = 1000;

void isolateEntrypoint(WriteType writeType) async {
  print('Isolate started with $writeType');
  Hive.init('./db');
  final box = await Hive.openBox('test.box');
  for (var i = 0; i < writeCount; ++i) {
    if (writeType == WriteType.num)
      await box.add(i);
    else
      await box.add('$i');
  }
  print(box.values.take(10));
  print('Isolate completed with $writeType');
  await Hive.close();
}

void main() async {
  for (var i = 0; i < 5; ++i) {
    final i1 = Isolate.spawn(isolateEntrypoint, WriteType.num);
    final i2 = Isolate.spawn(isolateEntrypoint, WriteType.alpha);
    await Future.wait([i1, i2]);

    Hive.init('./db');
    final box = await Hive.openBox('test.box');
    print(box.values.take(20));
    await Hive.close();
  }
}
```

```
Unhandled exception:
RangeError: Value not in range: -4
#0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:4623:5)
#1      _ByteBuffer.asUint8List (dart:typed_data-patch/typed_data_patch.dart:1929:5)
#2      new Uint8List.view (dart:typed_data:845:19)
#3      BinaryReaderImpl.peekBytes (package:hive/src/binary/binary_reader_impl.dart:68:22)
#4      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:70:31)
<asynchronous suspension>
#5      StorageBackendVm.initialize (package:hive/src/backend/storage_backend_vm.dart:85:25)
<asynchronous suspension>
#6      BoxBase.initialize (package:hive/src/box/box_base.dart:87:20)
#7      HiveImpl.openBoxInternal (package:hive/src/hive_impl.dart:92:15)
<asynchronous suspension>
#8      HiveImpl.openBox (package:hive/src/hive_impl.dart:72:23)
<asynchronous suspension>
#9      isolateEntrypoint
```

**Version**
 - Platform: Dart VM version: 2.6.0-dev.6.0 (Tue Oct 8 12:10:23 2019 +0200) on "windows_x64"
 - Hive version: "1.0.0"

**Discussion**

Many web server implementations (Aqueduct eg.) use isolates to process requests. I don't think above code sample is far fetched. What is your recommendation for using Hive in such environments?

**Comment by leisim** [comment]
Hive currently does not support concurrency.
While it is not impossible to make Hive "tread safe", it would be bad for performance.

I don't think Hive is a great fit for servers so I don't have any plans to support concurrency soon.

**Comment by daniel-v** [comment]
Extra bit: the Flutter projects I'm working on also use Isolates. One of them starts FlutterEngine in a service so that plugins can be used too. 

If nothing else, this should be mentioned in the docs.

If concurrency is not supported, maybe an exclusive file lock should be acquired on the box file to make sure that it can't be opened by multiple isolates. It's way worse to have a corrupted DB than getting an error for an unsupported use-case.

**Comment by leisim** [comment]
It is mentioned under limitations: https://docs.hivedb.dev/more/limitations

I will implement a file lock :+1:

**Comment by denghewenai** [comment]
> It is mentioned under limitations: https://docs.hivedb.dev/more/limitations
> 
> I will implement a file lock 👍

In file.lock doc has this :
Also note that advisory locks are on a process level. This means that several isolates in the same process can obtain an exclusive lock on the same file.So this file lock can not solve multiple isolates.
