### ISSUE TITLE
Can I store a Duration object in a Hive database?

### ISSUE THREAD

**Issue by flutternoob** [hivedb/hive#794]
**Question**
I am implementing a podcast player. I am currently developing the app for the Android platform and will implement it for iOS later. When the podcast is paused, the Duration position of the audio file has to be saved in the Hive database. When a given podcast is opened in the app, the saved Duration position has to be retrieved from the database and the playback should begin from the saved position I have a separate class which implements this feature in the app. I have initialized Hive in the app's ```main()``` function. However, every time I try to save the position to the database, I get the following error:

```
E/flutter (29975): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: Cannot write, unknown type: Duration. Did you forget to register an adapter?
E/flutter (29975): #0      BinaryWriterImpl.write (package:hive/src/binary/binary_writer_impl.dart:337:9)
E/flutter (29975): #1      BinaryWriterImpl.writeFrame (package:hive/src/binary/binary_writer_impl.dart:281:9)
E/flutter (29975): #2      StorageBackendVm.writeFrames.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:127:31)
E/flutter (29975): #3      StorageBackendVm.writeFrames.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:123:28)
E/flutter (29975): #4      ReadWriteSync.syncWrite.<anonymous closure> (package:hive/src/backend/vm/read_write_sync.dart:26:41)
E/flutter (29975): #5      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (29975): #6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (29975): <asynchronous suspension>
E/flutter (29975): #7      BoxImpl._writeFrames (package:hive/src/box/box_impl.dart:88:7)
E/flutter (29975): <asynchronous suspension>
E/flutter (29975): #8      ULTAudioLecturePositionDatabaseService.putAudioLecturePosition (package:united_lodge_theosophists/services/audio_lectures_position_database_service.dart:16:5)
E/flutter (29975): <asynchronous suspension>
E/flutter (29975): #9      _ULTAudioLecturesPlaybackBodyState.putAudioLecturePosition (package:united_lodge_theosophists/screens/audio_lectures/audio_lectures_playback_body.dart:59:5)
E/flutter (29975): <asynchronous suspension>
E/flutter (29975): #10     _ULTAudioLecturesPlaybackBodyState.build.<anonymous closure> (package:united_lodge_theosophists/screens/audio_lectures/audio_lectures_playback_body.dart:205:23)
E/flutter (29975): <asynchronous suspension>
E/flutter (29975): 
```

**Code sample**
```main()``` function implementation:

```
Future<void> main() async {
  //This line is needed to use the main function as a Future
  WidgetsFlutterBinding.ensureInitialized();

  //Database initialization
  Directory directory = await getApplicationDocumentsDirectory();
  Hive.init(directory.path);
  await ULTAudioLecturePositionDatabaseService.checkULTAudioLecturePositionDatabaseExists();
}
```

Class being used to carry out database functions:

```
class ULTAudioLecturePositionDatabaseService {
  ULTAudioLecturePositionDatabaseService._();

  static Future<void> checkULTAudioLecturePositionDatabaseExists() async {
    Hive.registerAdapter(ULTAudioLecturePositionAdapter());
    if (!(await Hive.boxExists("ultAudioLecturePositionBox"))){
      var ultAudioLecturePositionBox = await Hive.openBox("ultAudioLecturePositionBox");
    }
  }

  static Future<void> putAudioLecturePosition(String? audioLectureName, Duration? audioLecturePosition) async {
    var ultAudioLecturePositionBox = await Hive.openBox("ultAudioLecturePositionBox");
    await ultAudioLecturePositionBox.put(audioLectureName!, audioLecturePosition!);
  }

  static Future<Duration> getAudioLecturePosition(String? audioLectureName) async {
    var ultAudioLecturePositionBox = await Hive.openBox("ultAudioLecturePositionBox");
    if (ultAudioLecturePositionBox.containsKey(audioLectureName)) {
      Duration position = ultAudioLecturePositionBox.get(audioLectureName);
      return position;
    } else {
      return Duration.zero;
    }
  }
}
```

Hive model and its type adapter:

```
import 'package:hive/hive.dart';

part 'ult_audio_lectures_position_hive.g.dart';

@HiveType(typeId: 5)
class ULTAudioLecturePosition {
  @HiveField(0)
  final String? audioLectureName;

  @HiveField(1)
  final Duration? audioLecturePosition;

  ULTAudioLecturePosition({this.audioLectureName, this.audioLecturePosition});
}
```

```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'ult_audio_lectures_position_hive.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class ULTAudioLecturePositionAdapter
    extends TypeAdapter<ULTAudioLecturePosition> {
  @override
  final int typeId = 5;

  @override
  ULTAudioLecturePosition read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return ULTAudioLecturePosition(
      audioLectureName: fields[0] as String?,
      audioLecturePosition: fields[1] as Duration?,
    );
  }

  @override
  void write(BinaryWriter writer, ULTAudioLecturePosition obj) {
    writer
      ..writeByte(2)
      ..writeByte(0)
      ..write(obj.audioLectureName)
      ..writeByte(1)
      ..write(obj.audioLecturePosition);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ULTAudioLecturePositionAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
```

These are the methods within the widget that controls playback, that allows for retrieval and saving of the podcast player's Duration position in the database:

```
class ULTAudioLecturesPlaybackBody extends StatefulWidget {
  final String? audioFileName;
  final Map<dynamic, dynamic>? audioFileDetails;

  const ULTAudioLecturesPlaybackBody({Key? key, this.audioFileName, this.audioFileDetails})
      : super(key: key);

  @override
  _ULTAudioLecturesPlaybackBodyState createState() => _ULTAudioLecturesPlaybackBodyState();
}

class _ULTAudioLecturesPlaybackBodyState extends State<ULTAudioLecturesPlaybackBody> {
  Duration? _duration;
  Duration? _position;

  @override
  void initState() {
    super.initState();
    getAudioLecturePosition(widget.audioFileName);
  }

  @override
  void dispose() {
    putAudioLecturePosition(widget.audioFileName, _position);
    super.dispose();
  }

  Future<void> getAudioLecturePosition(String? audioLectureName) async {
    await ULTAudioLecturePositionDatabaseService.getAudioLecturePosition(audioLectureName)
        .then((position) => setState(() => _position = position));
  }

  Future<void> putAudioLecturePosition(String? audioLectureName, Duration? position) async {
    await ULTAudioLecturePositionDatabaseService.putAudioLecturePosition(audioLectureName, position);
  }
}
```

What should I do with my code to fix this bug? Thanks

**Version**
 - Platform: iOS, Android
 - Flutter version: 2.5
 - Hive version: 2.0.4

**Comment by bit-garden** [comment]
You are getting the error because there is no Duration adapter builtin to Hive, and it looks like you didn't provide your own. 

If you can reduce Duration down to a built-in datatype, you can store it. In this case, I would approach this by converting duration into an int, or writing the adapter to do that. 

Example adapter for Duration by seconds.
```
class DurationAdapter extends TypeAdapter<Duration> {
  int typeId = 0; // or whatever free id you have
  
  Duration read(BinaryReader reader) {
    return Duration(seconds: reader.read());
  }
   
  void writer(BinaryWriter writer, Duration obj){
    writer.write(obj.inSeconds);
  }
}
```

**Comment by flutternoob** [comment]
Which data types are supported by Hive out of the box? Is there a link that shows these supported data types? If not, please add a list of supported data types to the library's Readme. Thanks

**Comment by bit-garden** [comment]
`Hive supports all primitive types, List, Map, DateTime and Uint8List. If you want to store other objects, you have to register a TypeAdapter`

https://docs.hivedb.dev/#/custom-objects/type_adapters
