### ISSUE TITLE
Bad State: No element when putting a Map into a Box

### ISSUE THREAD

**Issue by marcelgarus** [hivedb/hive#80]
Is #50 really fixed? The following code throws this exact error with hive 1.0.0:

```dart
import 'package:hive/hive.dart';

void main(List<String> args) async {
  await Hive.init('.');
  var box = await Hive.openBox('number');
  box
    ..clear()
    ..putAll({
      1: 'a',
    });
}
```

Exception:

```
Unhandled exception:
Bad state: No element
#0      ListQueue.removeFirst (dart:collection/queue.dart:729:25)
#1      Keystore.cancelTransaction (package:hive/src/box/keystore.dart:143:33)
#2      BoxImpl._writeFrames (package:hive/src/box/box_impl.dart:126:16)
<asynchronous suspension>
#3      BoxImpl.putAll (package:hive/src/box/box_impl.dart:97:12)
#4      main (package:test/main.dart:10:9)
#5      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#12     HiveImpl.openBox (package:hive/src/hive_impl.dart)
#13     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#36     FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart)
#37     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#41     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#42     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

(sorry for opening a new issue, couldn't re-open #50)

**Comment by leisim** [comment]
Yes it is. Just use version `1.1.0-beta`. I'll release `beta2` soon and after that it will become the stable version.

**Comment by leisim** [comment]
The reason is that v`1.0.0` has a problem if you don't await the `Future`.

**Comment by marcelgarus** [comment]
Oh I see 😅 thanks

**Comment by leisim** [comment]
This has been resolved in `v1.1.0`.
