### ISSUE TITLE
#0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250:7) #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21:26) #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42:12) <asynchronous suspension> #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86:11) <asynchronous suspension> #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:116:9) <asynchronous suspension> #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:145:12) <asynchronous suspension> #6      HiveDb.init (package:swags_revised_original/Models/Database/HiveDb.dart:15:5) <asynchronous suspension> #7      main (package:swags_revised_original/main.dart:31:5) <asynchronous suspension>

### ISSUE THREAD

**Issue by Visakh417** [hivedb/hive#807]
My Db got crashed due to accidentally calling different openBox function.

**Comment by bakua** [comment]
I have the same issue.

```
#0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)\n#1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)\n#2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)\n<asynchronous suspension>\n#3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)\n<asynchronous suspension>\n#4      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)\n<asynchronous suspension>\n#5      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)\n<asynchronous suspension>\n#6      TeamRepository.getTeam (package:timesheet/src/lib/teams/repository/team_repository.dart:38)\n<asynchronous suspension>\n#7      UserRepository._map (package:timesheet/src/lib/auth/user_repository.dart:192)\n<asynchronous suspension>\n#8      DownSync._syncCurrentUsersTeamData (package:timesheet/src/lib/sync/sync.dart:92)\n<asynchronous suspension>
```
