### ISSUE TITLE
Random I/O error

### ISSUE THREAD

**Issue by r3flow** [hivedb/hive#813]
The test source available here:  https://pastebin.com/ijbsrV5F

OS: Win10 latest, hive package is the latest available on pub. Dart (2.14.0) is the latest version from the latest flutter (stable 2.5.0). (sdk: ">=2.14.0 <3.0.0")

The error occurs at a random point in the loop. There seems to be a race condition somewhere in the file handling.

```
cycle: 1654
Unhandled exception:
FileSystemException: Cannot rename file to 'C:\Users\User\Documents\contacts.hive', path = 'C:\Users\User\Documents\contacts.hivec' (OS Error: Access is denied.
, errno = 5)
#0      _File.rename.<anonymous closure> (dart:io/file_impl.dart:305:9)
<asynchronous suspension>
#1      StorageBackendVm.compact.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:187:7)
<asynchronous suspension>
#2      BoxBaseImpl.compact (package:hive/src/box/box_base_impl.dart:151:5)
<asynchronous suspension>
#3      BoxImpl._writeFrames (package:hive/src/box/box_impl.dart:95:5)
<asynchronous suspension>
#4      main (package:utils/hive_test.dart:63:7)
<asynchronous suspension>

Process finished with exit code 255
```

**Comment by anitaspieker** [comment]
Getting the same error.

**Comment by mohamedh83** [comment]
Anything new on this issue. I am still getting this error

**Comment by mohamedh83** [comment]
Anything new on that issue?  I'm getting the same error

**Comment by arthas1888** [comment]
same error
