### ISSUE TITLE
Got an error while using hive. After Clean and uninstalled the app it's resolved already. Please have a look.

### ISSUE THREAD

**Issue by m1narulal1** [hivedb/hive#932]
E/flutter ( 5685): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
E/flutter ( 5685): #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250:7)
E/flutter ( 5685): #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21:26)
E/flutter ( 5685): #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42:12)
E/flutter ( 5685): <asynchronous suspension>
E/flutter ( 5685): #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86:11)
E/flutter ( 5685): <asynchronous suspension>
E/flutter ( 5685): #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:111:9)
E/flutter ( 5685): <asynchronous suspension>
E/flutter ( 5685): #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:139:12)
E/flutter ( 5685): <asynchronous suspension>
E/flutter ( 5685): #6      HiveStore.openBox (package:titosapp/Store/HiveStore.dart:80:12)
E/flutter ( 5685): <asynchronous suspension>
E/flutter ( 5685): #7      HiveStore.initBox (package:titosapp/Store/HiveStore.dart:29:14)
E/flutter ( 5685): <asynchronous suspension>
E/flutter ( 5685): #8      main (package:titosapp/main.dart:44:3)
E/flutter ( 5685): <asynchronous suspension>
E/flutter ( 5685):

**Comment by PapyElGringo** [comment]
I've got the same issue
```
2022-03-20 20:28:24.261 18700-19576/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
    #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
    #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
    #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
    <asynchronous suspension>
    #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
    <asynchronous suspension>
    #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
    <asynchronous suspension>
    #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:139)
    <asynchronous suspension>
    #6      MessageListNotifier.initialize (package:tribu/data/tribu/message/message_list.notifier.dart:45)
    <asynchronous suspension>
    #7      Future.wait.<anonymous closure> (dart:async/future.dart:473)
    <asynchronous suspension>
    #8      initializeTribuProvider.<anonymous closure> (package:tribu/data/tribu/tribu.providers.dart:76)
    <asynchronous suspension>
    #9      _FutureProviderElementMixin._listenFuture.<anonymous closure> (package:riverpod/src/future_provider.dart:95)
    <asynchronous suspension>
    ```
