### ISSUE TITLE
Error in release version after some time of work

### ISSUE THREAD

**Issue by morfair** [hivedb/hive#952]
adb logcat:
```
04-19 15:34:28.611 16869 16903 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
04-19 15:34:28.611 16869 16903 E flutter : #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
04-19 15:34:28.611 16869 16903 E flutter : #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
04-19 15:34:28.611 16869 16903 E flutter : #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
04-19 15:34:28.611 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.611 16869 16903 E flutter : #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
04-19 15:34:28.611 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.611 16869 16903 E flutter : #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
04-19 15:34:28.611 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.611 16869 16903 E flutter : #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:139)
04-19 15:34:28.611 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.611 16869 16903 E flutter : #6      RegopRepo.loadUserData (package:regop37_driver/data/repo/regop37_repo.dart:79)
04-19 15:34:28.611 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.611 16869 16903 E flutter : #7      AuthCubit.fetchUser (package:regop37_driver/cubit/auth/auth_cubit.dart:109)
04-19 15:34:28.611 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.611 16869 16903 E flutter :
04-19 15:34:28.612 16869 16903 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
04-19 15:34:28.612 16869 16903 E flutter : #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
04-19 15:34:28.612 16869 16903 E flutter : #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
04-19 15:34:28.612 16869 16903 E flutter : #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
04-19 15:34:28.612 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.612 16869 16903 E flutter : #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
04-19 15:34:28.612 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.612 16869 16903 E flutter : #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
04-19 15:34:28.612 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.612 16869 16903 E flutter : #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:139)
04-19 15:34:28.612 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.612 16869 16903 E flutter : #6      RegopRepo.loadUserData (package:regop37_driver/data/repo/regop37_repo.dart:79)
04-19 15:34:28.612 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.612 16869 16903 E flutter : #7      AuthCubit.fetchUser (package:regop37_driver/cubit/auth/auth_cubit.dart:109)
04-19 15:34:28.612 16869 16903 E flutter : <asynchronous suspension>
04-19 15:34:28.612 16869 16903 E flutter :
```

**Comment by silverhairs** [comment]
A reproducible chunk of code would be really helpful.
