### ISSUE TITLE
Unknown type: DateTime

### ISSUE THREAD

**Issue by mhdkadi** [hivedb/hive#991]
**Steps to Reproduce**
I run the app on the browser, I tried to store a class whose property is Datetime

**Code sample**
@HiveType(typeId: 0)
class Dealer {
  Dealer({
    required this.expireTime,
  });

  @HiveField(0)
  DateTime expireTime;
}

**Version**
 - Platform:  Web
 - Flutter version:3.0.0
 - Hive version: 2.2.1

**Error**
Error: HiveError: Cannot write, unknown type: DateTime. Did you forget to register an adapter?
    at Object.throw_ [as throw] (http://localhost:64886/dart_sdk.js:5080:11)
at binary_writer_impl.BinaryWriterImpl.new.write (http://localhost:64886/packages/hive/src/box_collection.dart.lib.js:1355:21)

**Comment by Mohamad-Alkurdi** [comment]
I had the same issue after upgrading v2.0.5 to v2.1.0

**Comment by wptmdoorn** [comment]
I also have the same issue. 
Maybe defining the DateTime adapter locally in projects might be a temporary fix?

**Comment by pynner** [comment]
https://github.com/hivedb/hive/pull/983

Looks like it has been fixed here, just not released yet
